# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de32519f94ad0b29efbc2c4b952c31ec309f868ab4f3e5aa907e474f27bad8bca1648b0ce8eefbd38628b7fc375203616d323a1284ad98023825c11a7a167fc0

test:
  secret_key_base: 8c40b550779b5d7ff63380857dea888380ead0f28a054a286d0072b4b14c366cf2f7910652596cf3092d9f4ffb31ac491f7458cec5939a37e1f463457b00ce3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
